# Generated by Django 5.0.1 on 2024-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0003_staffapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
