# Generated by Django 5.0.1 on 2024-03-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0004_staffapplication_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
