# Generated by Django 5.0.1 on 2024-03-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0005_alter_staffapplication_street_address_delete_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='class_schedule',
            field=models.FileField(blank=True, null=True, upload_to='class_schedules/'),
        ),
    ]
