# Generated by Django 5.0.1 on 2024-03-27 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('staff_management', '0007_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.positions'),
        ),
    ]
