# Generated by Django 5.0.1 on 2024-03-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0008_alter_vacancy_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='quantity',
            new_name='available_quantity',
        ),
    ]
