# Generated by Django 5.0.1 on 2024-03-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0009_rename_quantity_vacancy_available_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
