# Generated by Django 5.0.1 on 2024-04-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0010_delete_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='approved',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
