# Generated by Django 5.0.1 on 2024-04-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0011_alter_staffapplication_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffapplication',
            name='approved',
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='approvalStatus',
            field=models.CharField(choices=[('yes', 'Approve'), ('no', 'Reject'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
