# Generated by Django 5.0.1 on 2024-04-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0012_remove_staffapplication_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffapplication',
            old_name='approvalStatus',
            new_name='approval_status',
        ),
    ]
