# Generated by Django 5.0.1 on 2024-04-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0013_rename_approvalstatus_staffapplication_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapplication',
            name='rejection_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
