# Generated by Django 5.0.1 on 2024-04-13 07:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0014_staffapplication_rejection_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='rejection_message',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
