# Generated by Django 5.0.1 on 2024-04-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0015_alter_staffapplication_rejection_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='class_schedule',
            field=models.FileField(blank=True, null=True, upload_to='static/class_schedules/'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='resume',
            field=models.FileField(upload_to='static/resumes/'),
        ),
    ]
