# Generated by Django 5.0.1 on 2024-04-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('event_management', '0018_eventvacancy_date_source_alter_eventvacancy_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
    ]
