# Generated by Django 5.0.1 on 2024-02-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerimage',
            old_name='image',
            new_name='full_image',
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='wide_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
