# Generated by Django 5.0.1 on 2024-04-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bannerimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerimage',
            old_name='image',
            new_name='image_url',
        ),
    ]
