# Generated by Django 5.0.1 on 2024-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_staffapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapplication',
            name='convicted_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
