# Generated by Django 5.0.1 on 2024-03-26 08:49

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_staffapplication_convicted_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('category_description', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='convicted_explanation',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('position_description', django_ckeditor_5.fields.CKEditor5Field()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.positionscategory')),
            ],
        ),
    ]
