# Generated by Django 5.0.1 on 2024-03-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_positionscategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='full_image',
        ),
        migrations.RemoveField(
            model_name='bannerimage',
            name='wide_image',
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='banner_image',
            field=models.ImageField(default=1, upload_to='banner_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='image_type',
            field=models.CharField(choices=[('full', 'Full'), ('wide', 'Wide')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
