# Generated by Django 5.0.1 on 2024-03-26 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_bannerimage_full_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerImage',
        ),
        migrations.AlterField(
            model_name='positions',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.positionscategory'),
        ),
    ]
