# Generated by Django 5.0.1 on 2024-02-12 05:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
    ]
