# Generated by Django 5.0.1 on 2024-02-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_purchase', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
