# Generated by Django 5.0.1 on 2024-02-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_purchase', '0003_ticketpurchase_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='new',
        ),
    ]
