# Generated by Django 5.0.1 on 2024-02-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_purchase', '0004_remove_ticketpurchase_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='payee_country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='payer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
