# Generated by Django 5.0.1 on 2024-02-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_purchase', '0005_ticketpurchase_email_ticketpurchase_payee_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
