# Generated by Django 5.0.1 on 2024-02-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_purchase', '0006_ticketpurchase_ticket_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketpurchase',
            old_name='ticket_pdf',
            new_name='ticket_qr',
        ),
    ]
