# Generated by Django 5.0.1 on 2024-02-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_purchase', '0007_rename_ticket_pdf_ticketpurchase_ticket_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='ticket_qr',
            field=models.FileField(blank=True, null=True, upload_to='static/tickets/'),
        ),
    ]
