# Generated by Django 5.0.1 on 2024-04-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_purchase', '0009_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
