# Generated by Django 5.0.1 on 2024-02-20 15:01

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='static/event_images/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ticket_available', models.BooleanField(default=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('special_guests', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('parking_info', models.CharField(blank=True, max_length=200, null=True)),
                ('transportation_options', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('food_and_beverage', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('rules_and_regulations', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('sponsors', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('organization_image', models.ImageField(upload_to='static/organizer_images/')),
                ('organization_description', django_ckeditor_5.fields.CKEditor5Field()),
                ('organization_website', models.URLField(blank=True, null=True)),
                ('organization_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organization_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
