# Generated by Django 5.0.1 on 2024-02-12 05:51

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='event_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
