# Generated by Django 5.0.1 on 2024-02-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_rename_ticketdetails_ticketdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
