# Generated by Django 5.0.1 on 2024-02-12 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_event_image_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
