# Generated by Django 5.0.1 on 2024-02-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_remove_attendee_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
