# Generated by Django 5.0.1 on 2024-02-12 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_rename_time_event_start_time_event_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='event_images/'),
            preserve_default=False,
        ),
    ]
