# Generated by Django 5.0.1 on 2024-04-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('event_management', '0011_eventvacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.positions'),
        ),
    ]
