# Generated by Django 5.0.1 on 2024-04-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0013_staffassignment_staff1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffassignment',
            name='staff1',
        ),
    ]
