# Generated by Django 5.0.1 on 2024-04-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0016_staffassignment_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdetail',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticketdetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
        migrations.DeleteModel(
            name='TicketDetail',
        ),
    ]
