# Generated by Django 5.0.1 on 2024-04-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0017_remove_ticketdetail_event_remove_ticketdetail_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvacancy',
            name='date_source',
            field=models.CharField(choices=[('event', 'Use Event Date'), ('custom', 'Use Custom Date')], default='event', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventvacancy',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
