# Generated by Django 5.0.1 on 2024-04-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0018_eventvacancy_date_source_alter_eventvacancy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvacancy',
            name='payment_hourly',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
