# Generated by Django 5.0.1 on 2024-04-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0019_eventvacancy_payment_hourly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventvacancy',
            name='payment_hourly',
        ),
    ]
