# Generated by Django 5.0.1 on 2024-04-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0020_remove_eventvacancy_payment_hourly'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvacancy',
            name='payment_hourly',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
    ]
