# Generated by Django 5.0.1 on 2024-04-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0022_eventvacancy_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventvacancy',
            name='duration',
        ),
    ]
