# Generated by Django 5.0.1 on 2024-04-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0023_remove_eventvacancy_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
