# Generated by Django 5.0.1 on 2024-04-27 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0025_removeduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='removeduser',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='eventvacancy',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True, 'is_superuser': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='removeduser',
            name='event_vacancy',
        ),
        migrations.RemoveField(
            model_name='removeduser',
            name='user',
        ),
    ]
