# Generated by Django 5.0.1 on 2024-04-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0026_alter_removeduser_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffAssignment',
        ),
    ]
