# Generated by Django 5.0.1 on 2024-04-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0027_delete_staffassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvacancy',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=10),
        ),
    ]
