# Generated by Django 5.0.1 on 2024-04-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0028_eventvacancy_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemovedUser',
        ),
        migrations.AddField(
            model_name='eventvacancy',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
