# Generated by Django 5.0.1 on 2024-04-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0029_delete_removeduser_eventvacancy_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventvacancy',
            name='date_source',
        ),
    ]
